title: PolicySpatial # your name (or website title) here
logo: "/images/oooo.plus_85.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Nicholas Scott, a student of data and the benefits it can bring to citizens around me. I intend for this platform to be a live display of city policies
  with particular attention to transportation, economic development, environmental economics, and social cost-benefit analysis.
<br></br>
  If you'd like to contact me, please send an email here: nick@policyspatial.com
<br></br>

Link: <a href="https://www.linkedin.com/in/nicholastscott/">View My LinkedIn Profile</a>
<br></br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
