title: PolicySpatial # your name (or website title) here
logo: "/images/IMG_1756?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Nicholas Scott, a student of data and the benefits it can bring to citizens around me. <br></br>
  I intend for this platform to be a live display of city policies <br><br>
  with particular attention to health disparities, economic development, environmental racism, and social justice.
  <br><br>
  If you'd like to contact me, please send an email here: nick@policyspatial.com 
  <br><br>
  <a href="https://www.linkedin.com/in/nicholastscott/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
